import type { ThemeBackgroundDefinition } from "@/lib/themes/types";

function createBackground(
  image: string,
  options: Omit<ThemeBackgroundDefinition, "image">
): ThemeBackgroundDefinition {
  return {
    image,
    ...options,
  };
}

export const THEME_BACKGROUNDS = {
  "midnight-gold": createBackground("/images/themes/midnight-gold.webp", {
    position: "right top",
    mobilePosition: "68% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.24,
    overlay:
      "linear-gradient(180deg, rgba(10,10,10,0.12) 0%, rgba(10,10,10,0.02) 32%, rgba(10,10,10,0.22) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "right top",
    previewSize: "cover",
    previewOpacity: 0.4,
  }),
  "arctic-light": createBackground("/images/themes/arctic-light.webp", {
    position: "center top",
    mobilePosition: "56% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.3,
    overlay:
      "linear-gradient(180deg, rgba(255,255,255,0.14) 0%, rgba(255,255,255,0.04) 38%, rgba(245,249,255,0.12) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.45,
  }),
  "ocean-breeze": createBackground("/images/themes/ocean-breeze.webp", {
    position: "center top",
    mobilePosition: "58% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.26,
    overlay:
      "linear-gradient(180deg, rgba(242,251,253,0.14) 0%, rgba(242,251,253,0.02) 38%, rgba(235,249,251,0.16) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.42,
  }),
  "forest-explorer": createBackground("/images/themes/forest-explorer.webp", {
    position: "center top",
    mobilePosition: "60% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.26,
    overlay:
      "linear-gradient(180deg, rgba(19,28,22,0.22) 0%, rgba(19,28,22,0.06) 36%, rgba(19,28,22,0.28) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.48,
  }),
  sakura: createBackground("/images/themes/sakura.webp", {
    position: "right top",
    mobilePosition: "74% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.26,
    overlay:
      "linear-gradient(180deg, rgba(255,246,248,0.08) 0%, rgba(255,246,248,0.02) 40%, rgba(255,246,248,0.14) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "right top",
    previewSize: "cover",
    previewOpacity: 0.5,
  }),
  "cyber-neon": createBackground("/images/themes/cyber-neon.webp", {
    position: "center top",
    mobilePosition: "58% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.26,
    overlay:
      "linear-gradient(180deg, rgba(8,0,15,0.18) 0%, rgba(8,0,15,0.04) 42%, rgba(8,0,15,0.22) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.48,
  }),
  "royal-purple": createBackground("/images/themes/royal-purple.webp", {
    position: "center top",
    mobilePosition: "64% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.28,
    overlay:
      "linear-gradient(180deg, rgba(19,10,34,0.18) 0%, rgba(19,10,34,0.05) 34%, rgba(19,10,34,0.2) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.46,
  }),
  "desert-sand": createBackground("/images/themes/desert-sand.webp", {
    position: "center bottom",
    mobilePosition: "60% bottom",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.25,
    overlay:
      "linear-gradient(180deg, rgba(251,243,230,0.08) 0%, rgba(251,243,230,0.02) 38%, rgba(248,239,224,0.16) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center bottom",
    previewSize: "cover",
    previewOpacity: 0.45,
  }),
  "emerald-night": createBackground("/images/themes/emerald-night.webp", {
    position: "center top",
    mobilePosition: "58% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.25,
    overlay:
      "linear-gradient(180deg, rgba(4,18,13,0.2) 0%, rgba(4,18,13,0.04) 36%, rgba(4,18,13,0.24) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.47,
  }),
  aurora: createBackground("/images/themes/aurora.webp", {
    position: "center top",
    mobilePosition: "56% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.28,
    overlay:
      "linear-gradient(180deg, rgba(7,11,30,0.22) 0%, rgba(7,11,30,0.04) 38%, rgba(7,11,30,0.28) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.5,
  }),
  "nordic-frost": createBackground("/images/themes/nordic-frost.webp", {
    position: "center top",
    mobilePosition: "54% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.3,
    overlay:
      "linear-gradient(180deg, rgba(247,249,251,0.12) 0%, rgba(247,249,251,0.02) 40%, rgba(244,247,250,0.16) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.42,
  }),
  "japanese-ink": createBackground("/images/themes/japanese-ink.webp", {
    position: "right top",
    mobilePosition: "70% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.24,
    overlay:
      "linear-gradient(180deg, rgba(247,243,234,0.1) 0%, rgba(247,243,234,0.02) 42%, rgba(244,239,231,0.16) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "right top",
    previewSize: "cover",
    previewOpacity: 0.5,
  }),
  "matcha-garden": createBackground("/images/themes/matcha-garden.webp", {
    position: "right top",
    mobilePosition: "68% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.3,
    overlay:
      "linear-gradient(180deg, rgba(246,243,231,0.08) 0%, rgba(246,243,231,0.02) 42%, rgba(241,239,227,0.18) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "right top",
    previewSize: "cover",
    previewOpacity: 0.48,
  }),
  mediterranean: createBackground("/images/themes/mediterranean.webp", {
    position: "center top",
    mobilePosition: "60% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.28,
    overlay:
      "linear-gradient(180deg, rgba(251,248,241,0.08) 0%, rgba(251,248,241,0.02) 40%, rgba(247,243,235,0.14) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.45,
  }),
  "tropical-lagoon": createBackground("/images/themes/tropical-lagoon.webp", {
    position: "center top",
    mobilePosition: "60% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.3,
    overlay:
      "linear-gradient(180deg, rgba(245,242,232,0.06) 0%, rgba(245,242,232,0.02) 38%, rgba(241,237,227,0.18) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.46,
  }),
  "sunset-journey": createBackground("/images/themes/sunset-journey.webp", {
    position: "center bottom",
    mobilePosition: "58% bottom",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.28,
    overlay:
      "linear-gradient(180deg, rgba(251,241,231,0.08) 0%, rgba(251,241,231,0.02) 40%, rgba(247,237,227,0.14) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center bottom",
    previewSize: "cover",
    previewOpacity: 0.46,
  }),
  terracotta: createBackground("/images/themes/terracotta.webp", {
    position: "center top",
    mobilePosition: "62% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.24,
    overlay:
      "linear-gradient(180deg, rgba(246,237,225,0.08) 0%, rgba(246,237,225,0.02) 38%, rgba(241,231,219,0.16) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.44,
  }),
  "vintage-explorer": createBackground("/images/themes/vintage-explorer.webp", {
    position: "center top",
    mobilePosition: "56% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.3,
    overlay:
      "linear-gradient(180deg, rgba(244,236,216,0.1) 0%, rgba(244,236,216,0.02) 38%, rgba(239,231,209,0.16) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.48,
  }),
  alpine: createBackground("/images/themes/alpine.webp", {
    position: "center top",
    mobilePosition: "54% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.3,
    overlay:
      "linear-gradient(180deg, rgba(244,247,248,0.1) 0%, rgba(244,247,248,0.02) 38%, rgba(239,243,244,0.14) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.45,
  }),
  "autumn-trail": createBackground("/images/themes/autumn-trail.webp", {
    position: "center top",
    mobilePosition: "60% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.27,
    overlay:
      "linear-gradient(180deg, rgba(246,237,224,0.08) 0%, rgba(246,237,224,0.02) 38%, rgba(242,231,215,0.16) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.48,
  }),
  "cherry-blossom-night": createBackground("/images/themes/cherry-blossom-night.webp", {
    position: "right top",
    mobilePosition: "74% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.28,
    overlay:
      "linear-gradient(180deg, rgba(18,16,29,0.2) 0%, rgba(18,16,29,0.04) 42%, rgba(18,16,29,0.28) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "right top",
    previewSize: "cover",
    previewOpacity: 0.52,
  }),
  "northern-lights": createBackground("/images/themes/northern-lights.webp", {
    position: "center top",
    mobilePosition: "58% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.3,
    overlay:
      "linear-gradient(180deg, rgba(5,10,18,0.22) 0%, rgba(5,10,18,0.04) 40%, rgba(5,10,18,0.28) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.5,
  }),
  "solarized-traveler": createBackground("/images/themes/solarized-traveler.webp", {
    position: "center top",
    mobilePosition: "54% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.28,
    overlay:
      "linear-gradient(180deg, rgba(247,241,227,0.1) 0%, rgba(247,241,227,0.02) 38%, rgba(242,237,224,0.14) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.42,
  }),
  "coffee-house": createBackground("/images/themes/coffee-house.webp", {
    position: "center top",
    mobilePosition: "62% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.25,
    overlay:
      "linear-gradient(180deg, rgba(237,225,211,0.1) 0%, rgba(237,225,211,0.02) 40%, rgba(232,219,203,0.16) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.44,
  }),
  monochrome: createBackground("/images/themes/monochrome.webp", {
    position: "center top",
    mobilePosition: "58% top",
    size: "cover",
    mobileSize: "cover",
    repeat: "no-repeat",
    opacity: 0.22,
    overlay:
      "linear-gradient(180deg, rgba(255,255,255,0.14) 0%, rgba(255,255,255,0.02) 40%, rgba(246,247,248,0.12) 100%)",
    overlayOpacity: 1,
    attachment: "scroll",
    previewPosition: "center top",
    previewSize: "cover",
    previewOpacity: 0.4,
  }),
} satisfies Record<string, ThemeBackgroundDefinition>;
